# Generated by Django 6.0.4 on 2026-04-14 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('partial', 'Partial — some items unavailable'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('order_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField()),
                ('quantity_fulfilled', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('held', 'Held at farm'), ('confirmed', 'Confirmed'), ('unavailable', 'Unavailable')], default='pending', max_length=15)),
                ('fulfillment_farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farms.farm')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farms.marketlisting')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservations.order')),
            ],
        ),
    ]
