# Generated by Django 6.0.4 on 2026-04-14 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=60)),
                ('token', models.CharField(blank=True, help_text='UUID — lets customer access orders without login', max_length=64, unique=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-joined'],
            },
        ),
        migrations.CreateModel(
            name='FulfillmentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Primary'), (2, 'Secondary'), (3, 'Tertiary')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='customers.customer')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
            ],
            options={
                'ordering': ['customer', 'priority'],
                'unique_together': {('customer', 'farm')},
            },
        ),
    ]
