# Generated by Django 6.0.4 on 2026-04-14 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True)),
                ('api_url', models.URLField(help_text='Base URL of farm Django instance e.g. https://raggedgloryfarm.com')),
                ('api_key', models.CharField(blank=True, help_text='Future auth — leave blank for now', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CachedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('eggs', 'Eggs'), ('veg', 'Vegetables'), ('fruit', 'Fruit'), ('bread', 'Bread & Baked'), ('preserve', 'Preserves'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='farms.farm')),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('farm', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_date', models.DateField()),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_label', models.CharField(default='each', max_length=40)),
                ('menu_entry_id', models.PositiveIntegerField()),
                ('location_note', models.CharField(blank=True, max_length=200)),
                ('market_address', models.CharField(blank=True, max_length=300)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='farms.farm')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='farms.cachedproduct')),
            ],
            options={
                'ordering': ['market_date', 'product__category', 'product__name'],
                'unique_together': {('farm', 'menu_entry_id')},
            },
        ),
    ]
